changelog:
  categories:
    - title: Features
      labels: [enhancement]
    - title: Bug fixes
      labels: [bug]
    - title: Documentation
      labels: [documentation]
    - title: Maintenance
      labels: [maintenance]
  exclude:
    labels: [skip-changelog]
